---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: default-mosquitto
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-rook-ceph-cluster
    - name: volsync
    #- name: monitoring-kube-prometheus-stack
  path: "./kubernetes/virtops/apps/default/mosquitto/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes  
  wait: false
  interval: 15m
  retryInterval: 1m
  timeout: 5m
