ansible_user: ENC[AES256_GCM,data:Bq5yjw==,iv:pXi53SzqlIzckXn56n3ht+wpWWOCWXvIR31KUr3N9Vk=,tag:30lhJ71pC57iQX7K1aEDxQ==,type:str]
ansible_password: ENC[AES256_GCM,data:Ej8OQw==,iv:8h/qyhQtmCKdfgLHHgtKCl8PQ9PcIMoJQrZtuB7nbX4=,tag:PQ9Fa1H7ouSLs9ossGlHpw==,type:str]
cloudflare:
    email: ENC[AES256_GCM,data:2+W8U+Kq0/ykwtdvtQ==,iv:3SSeGgnChwqtbYO0yLMkkxUeV1DoUbIN4KDGmdHNWkI=,tag:wPzZ9nO8nE94djEPiO7Peg==,type:str]
    api_token: ENC[AES256_GCM,data:+bULGNjTpAXLOqgOnUlAax8xQ7E987cx19Fqg2gCM+hVVXcKwGi7dw==,iv:TEK7MzyV9MzP2z1fa/aysJZftwAeBsyRYPHNu7/yoVs=,tag:1QInq+qdMwCB3hQL2rHznQ==,type:str]
certificate:
    common_name: ENC[AES256_GCM,data:b5sDxFv4WieQ7BzkUL7/oELfIA+g2hy6lTjU,iv:tnJKCNRZU2eGLhpmzC8v8M9gsUyQaPg09QGDjbSm8Xk=,tag:CMheWkFWHzOwpkfxH1FIKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uk0y2ahfavgsgqvrtg5a22w5gytpdmjuatxtcw6kntmxhlcgreesuwzw5s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMjBiN0swVEFYaEY5aE5K
            b0NXTk1IWVp5dkNxc0MzM2wxbVkwbFQrQ1hzCk9pMVEzb1BodFdrd2c2Nk52dEMx
            ZVc4RWt1LytaWVk0VUQ2TEluTlJlWjQKLS0tIHIxYU01WTVnamdCQ205eDRKMFNE
            eVI3bGlUVCsvd1IwMm03eDYxWmZFaUkKPS4xu8nPZVZDbfcZY5Wdya44KptY+z4I
            Mx1B0xT+VSKjvRJuBf9pJiE/7yQZpb8IWEXGqtrt0lMoSW5Esu5EQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-08T11:17:09Z"
    mac: ENC[AES256_GCM,data:xRrcE7pepOne9Vvfo77Qerqs8/R2Hwe5Y9m33SnLDGHroSCNTJNlnRf1h+eV7RC7aI80Vd8CaJWG7wGVheqxScdLXaBeS+SMXYaFvmuKaO2EqzgqGg6bZbEWUb+pnBoxNr93eGKoUxRLp/t/iLeAye4KdwPIEmM3sFpYZKg5i24=,iv:cY2mizE9ktO6MxF5Bbx7qeT+kvLnh6hvehWQszSCoMg=,tag:eqB1NuH/0qtRa26ryVjxIQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
