---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app nextdns-exporter-servers
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: 'true'
    image:
      repository: ghcr.io/raylas/nextdns-exporter
      tag: 0.5.2@sha256:ea0e0ef50211fc0e70eea20c85118b45cd68d3d12d84994421d3f9afa0621908
    env:
      TZ: '${TIMEZONE}'
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        ports:
          http:
            enabled: false
          metrics:
            enabled: true
            port: 9948
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 5m
            scrapeTimeout: 30s
    