---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Immich
        DB_DATABASE_NAME: &dbname immich
        DB_HOSTNAME: &dbhost postgres-rw.default.svc.cluster.local
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        DB_USERNAME: "{{ .DB_USERNAME }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        TYPESENSE_API_KEY: "{{ .TYPESENSE_API_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_PASS: "{{ .DB_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: "{{ .DB_USERNAME }}"
  dataFrom:
    - extract:
        key: IMMICH
    - extract:
        key: CLOUDNATIVE_PG
