---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-pgadmin
  namespace: flux-system
spec:
  path: ./kubernetes/virtops/apps/default/pgadmin/app
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  #healthChecks:
  #  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
  #    kind: HelmRelease
  #    name: pgadmin
  #    namespace: default
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-volsync
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
