---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: default-pgadmin
  namespace: flux-system
spec:
  path: ./kubernetes/virtops/apps/default/pgadmin/app
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  dependsOn:
    - name: flux-system-external-secrets-stores
    - name: cluster-apps-rook-ceph-cluster
    - name: volsync
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
