---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-overseerr
  namespace: flux-system
spec:
  dependsOn:
    - name: rook-ceph-cluster
    - name: volsync
  path: ./kubernetes/virtops/apps/media/overseerr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
