---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./rbac.yaml
labels:
  - pairs:
      app.kubernetes.io/name: weave-gitops
      app.kubernetes.io/instance: weave-gitops
