---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-karma
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-kube-prometheus-stack
  path: ./kubernetes/virtops/apps/monitoring/karma/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
