---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scrypted
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/koush/scrypted
      tag: 20-jammy-full-v0.55.0@sha256:268a10d447910dc55985d89ff3a39c5df3c6e6a9105c1745c7861c64e6cb1627
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        ports:
          http:
            port: &web-port 11080
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: &host "scrypted.${ORG_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      cache:
        enabled: true
        mountPath: /.cache
        type: emptyDir
      cache-npm:
        enabled: true
        mountPath: /.npm
        type: emptyDir
    volumeClaimTemplates:
      - name: config
        mountPath: /server/volume
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
    #nodeSelector:
    #  node-role.kubernetes.io/worker: "true"
    #  intel.feature.node.kubernetes.io/gpu: "true"
    #resources:
    #  requests:
    #    gpu.intel.com/i915: 1
    #    cpu: 10m
    #    memory: 250Mi
    #  limits:
    #    gpu.intel.com/i915: 1
    #    memory: 2000Mi
