---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: radarr-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # PUSHOVER_TOKEN, RADARR__API_KEY
        key: RADARR
    - extract:
        # PUSHOVER_USER_KEY
        key: pushover
