---
    # 
    apiVersion: monitoring.coreos.com/v1alpha1
    kind: ScrapeConfig
    metadata:
      name: node-exporter
      namespace: monitoring
    spec:
      staticConfigs:
        - targets:
            - gateway.${NET_DOMAIN}:9100
            - pbs.${NET_DOMAIN}:9100
      metricsPath: /metrics