#---
#    # yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/monitoring.coreos.com/scrapeconfig_v1alpha1.json
#apiVersion: monitoring.coreos.com/v1alpha1
#kind: ScrapeConfig
#metadata:
#    name: vyos-gatus
#    namespace: monitoring
#spec:
#    staticConfigs:
#    - targets: ["status.turbo.ac"]
#    metricsPath: /metrics
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
    name: vyos-speedtest-exporter
    namespace: monitoring
spec:
    staticConfigs:
    - targets: ["gateway.${NET_DOMAIN}:9798"]
    metricsPath: /metrics
        