---
# 
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
    name: vyos-speedtest-exporter
    namespace: monitoring
spec:
    staticConfigs:
    - targets: ["gateway.${NET_DOMAIN}:9798"]
    metricsPath: /metrics
---
# 
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
    name: vyos-podman-exporter
    namespace: monitoring
spec:
    staticConfigs:
    - targets: ["gateway.${NET_DOMAIN}:9882"]
    metricsPath: /metrics