---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/gitrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-ops-kubernetes
  namespace: flux-system
spec:
  interval: 30m
  url: ssh://git@github.com/fisherbln/virt-ops
  ref:
    branch: main
  secretRef:
    name: github-deploy-key
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/kubernetes
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/virtops/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: flux
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
      - kind: Secret
        name: cluster-secrets
        optional: false
