---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externaldns-secrets
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: externaldns-external-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: CLOUDFLARE
