---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: externaldns-external
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.12.2
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: &name externaldns-external
    
    #domainFilters:
    #  - ${ORG_DOMAIN}

    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: externaldns-external-secrets
            key: api-token

    extraArgs:
      #- --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      #- --crd-source-kind=DNSEndpoint
      - --cloudflare-proxied
      - --annotation-filter=external-dns.alpha.kubernetes.io/target

    policy: sync
    provider: cloudflare
    
    sources:
      - ingress
      #- crd

    txtPrefix: "k8s."

    txtOwnerId: default
    
    serviceMonitor:
      enabled: true
    
    podAnnotations:
      secret.reloader.stakater.com/reload: externaldns-external-secrets
    
    #postRenderers:
    #- kustomize:
    #    patches:
    #      - target:
    #          version: v1
    #          kind: Deployment
    #          name: *name
    #        patch: |
    #          - op: add
    #            path: /spec/template/spec/enableServiceLinks
    #            value: false
   