---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: externaldns-external
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: &name externaldns-external
    interval: 2m
    # logLevel: debug
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: externaldns-external-secrets
            key: api-token

    extraArgs:
      #- --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      #- --crd-source-kind=DNSEndpoint
      - --cloudflare-proxied
      - --annotation-filter=external-dns.alpha.kubernetes.io/target

    policy: sync
    sources:
      - ingress
      #- crd
    txtPrefix: "k8s."
    txtOwnerId: default
    domainFilters:
      - ${ORG_DOMAIN}
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: externaldns-external-secrets
   