---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.ROOT_DIR}}/kubernetes/virtops"
  PROVISION_DIR: "{{.ROOT_DIR}}/infrastructure"
  TERRAFORM_DIR: "{{.PROJECT_DIR}}/infrastructure/terraform"
  TALOS_DIR: "{{.PROJECT_DIR}}/infrastructure/talos/virtops"
  TALOS_PRIMARY_NODE: "10.28.28.71"
  TALOS_CONTROL_NODES: "10.28.28.71,10.28.28.72,10.28.28.73"
  TALOS_WORKER_NODES: "10.28.28.61,10.28.28.62,10.28.28.63"
  CLUSTER: virtops
  GITHUB_USER: fisherbln
  GITHUB_REPO: virt-ops
  GITHUB_BRANCH: main

env:
  KUBECONFIG: ./infrastructure/talos/virtops/kubeconfig

includes:
  cl: .taskfiles/Cluster/Tasks.yml
  es: .taskfiles/ExternalSecrets/Tasks.yml
  fx: .taskfiles/Flux/Tasks.yml
  ku: .taskfiles/Kubernetes/Tasks.yml
  vs: .taskfiles/VolSync/Tasks.yml
  ta: .taskfiles/Talos/Tasks.yml

tasks:

  default:
    silent: true
    cmds: ["task -l"]
