---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/virtops/apps/cert-manager/cert-manager/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-cert-manager-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cert-manager
    - name: cluster-apps-external-secrets-stores
  interval: 10m
  path: "./kubernetes/virtops/apps/cert-manager/cert-manager/issuers"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  
