---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-thanos
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: system-democratic-csi-local-path
    - name: flux-system-external-secrets-stores
  path: "./kubernetes/virtops/apps/monitoring/thanos/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
