---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zalando-postgres-pod-secrets
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: zalando-postgres-pod-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: postgres
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        CLONE_AWS_ACCESS_KEY_ID: postgres
        CLONE_AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: ZALANDO_POSTGRES
      #rewrite:
      #  - regexp:
      #      source: "[-]"
      #      target: "_"
      #  - regexp:
      #      source: "(.*)"
      #      target: "minio_$1"
