---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: ceph-pve-external
  namespace: rook-ceph
spec:
  external:
    enable: true
  dataDirHostPath: /var/lib/rook
  cephVersion:
    image: quay.io/ceph/ceph:v17.2.6@sha256:a9c07f260b818e8085f5514c474048ee1ac174e5f7cc52fff79573c32ff75582
  crashCollector:
    disable: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
  monitoring:
    enabled: true
    externalMgrEndpoints:
      # these are the PVE nodes
      - ip: "10.28.1.51"
      - ip: "10.28.1.52"
      - ip: "10.28.1.53"
    externalMgrPrometheusPort: 9283
