---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ceph-cluster.yaml
  - ./ceph-monitor.yaml
  - ./ceph-prometheus.yaml
  - ./secrets.sops.yaml
  - ./storage-class.yaml
labels:
  - pairs:
      app.kubernetes.io/name: cluster-apps-rook-ceph-cluster
      app.kubernetes.io/instance: cluster-apps-rook-ceph-cluster
      app.kubernetes.io/part-of: rook-ceph
      