---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-global
    #name: vault-global
  target:
    name: esphome-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  #data:
  #  - secretKey: secrets.yaml
  #    remoteRef:
  #      key: ESPHOME
  #      #key: esphome
  #      property: secrets.yaml
  dataFrom:
    - extract:
        key: ESPHOME
