---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app esphome
  namespace: home
  annotations:
    coredns.io/hostname: esphome.{NET_DOMAIN}
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 5
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/esphome/esphome
      tag: 2023.3.2
    env:
      TZ: ${TIMEZONE}
      ESPHOME_DASHBOARD_USE_PING: "true"
    service:
      main:
        ports:
          http:
            port: 6052
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: esphome-config
      secrets:
        enabled: true
        type: custom
        readOnly: true
        volumeSpec:
          secret:
            secretName: esphome-secrets
        subPath:
          - path: secrets.yaml
            mountPath: /config/secrets.yaml
      esphome-config:
        enabled: true
        type: custom
        readOnly: true
        volumeSpec:
          configMap:
            name: esphome-config
        subPath:
          - path: air-gradient-office.yaml
            mountPath: /config/air-gradient-office.yaml
          - path: air-gradient-master.yaml
            mountPath: /config/air-gradient-master.yaml
          - path: air-gradient-utility.yaml
            mountPath: /config/air-gradient-utility.yaml
          - path: air-gradient-upstairs.yaml
            mountPath: /config/air-gradient-upstairs.yaml
          - path: grill.yaml
            mountPath: /config/grill.yaml
          - path: monofont.ttf
            mountPath: /font/monofont.ttf


    podAnnotations:
      secret.reloader.stakater.com/reload: esphome-secrets
      configmap.reloader.stakater.com/reload: esphome-config

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: ipv4.${ORG_DOMAIN}
          traefik.ingress.kubernetes.io/router.middlewares: networking-org-auth@kubernetescrd
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          #traefik.ingress.kubernetes.io/affinity: "true"
          #traefik.ingress.kubernetes.io/router.tls: "true"
          hajimari.io/enable: "true"
          hajimari.io/appName: *app
          hajimari.io/instance: "org"
          hajimari.io/icon: simple-icons:esphome
        hosts:
          - host: &host "esphome.${ORG_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "tls-{{ .Release.Name }}"
