---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./config
  - ./pvc.yaml
  - ./external-secrets.yaml
  - ./helm-release.yaml
  - ./replicationsource.yaml
  #- volsync-secrets.sops.yaml
  # - volsync-replication-destination.yaml
  # - volsync-replication-source.yaml
commonLabels:
  app.kubernetes.io/name: esphome
  app.kubernetes.io/instance: esphome
  app.kubernetes.io/managed-by: fluxcd.io
