---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: influxdb
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-global
    #name: vault-backend-global
  target:
    name: influxdb-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        # admin-username, admin-password, admin-token
        key: INFLUXDB
        #key: influxdb
