---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app influxdb
  namespace: default
spec:
  interval: 60m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.1
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
      interval: 60m
  #dependsOn:
  #  - name: rook-ceph-cluster
  #    namespace: rook-ceph
  #postRenderers:
  #  - kustomize:
  #      patchesStrategicMerge:
  #        - apiVersion: v1
  #          kind: Service
  #          metadata:
  #            name: influxdb
  #          spec:
  #            externalIPs:
  #              - ${SVC_INFLUX_ADDR_V4}
  #            externalTrafficPolicy: Local
  # Values link: https://github.com/influxdata/helm-charts/blob/master/charts/influxdb2/values.yaml
  values:
    fullnameOverride: *app
    image:
      repository: influxdb
      tag: 2.6.1-alpine

    pdb:
      create: false
    service:
      type: LoadBalancer
      #loadBalancerIP: "${SVC_INFLUX_ADDR_V4}"
      #annotations:
      #  coredns.io/hostname: influx.${ORG_DOMAIN}

    env:
      - name: TZ
        value: "${TIMEZONE}"

    adminUser:
      organization: "primary"
      # user: "admin"
      #retention_policy: "60d"
      #bucket: "default"

    persistence:
      enabled: true
      existingClaim: "influxdb-data"

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
      hostname: influx.${ORG_DOMAIN}
      path: /
      tls: true

  valuesFrom:
    - targetPath: adminUser.user
      kind: Secret
      name: influxdb-secrets
      valuesKey: admin-username
    - targetPath: adminUser.password
      kind: Secret
      name: influxdb-secrets
      valuesKey: admin-password
    - targetPath: adminUser.token
      kind: Secret
      name: influxdb-secrets
      valuesKey: admin-token
