---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-snapshot-controller
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    #- name: cluster-apps-kube-prometheus-stack
    - name: cluster-apps-rook-ceph-cluster
  path: "./kubernetes/virtops/apps/kube-system/snapshot-controller/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
