---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-externaldns-shared
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./kubernetes/virtops/apps/networking/external-dns/shared"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-externaldns-external
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-kube-prometheus-stack
  path: "./kubernetes/virtops/apps/networking/external-dns/external"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  #healthChecks:
  #  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
  #    kind: HelmRelease
  #    name: externaldns-external
  #    namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-externaldns-internal
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-kube-prometheus-stack
  path: "./kubernetes/virtops/apps/networking/external-dns/internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  #healthChecks:
  #  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
  #    kind: HelmRelease
  #    name: externaldns-internal
  #    namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m