---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-externaldns-shared
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./kubernetes/virtops/apps/networking/external-dns/shared"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-externaldns-external
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
  path: "./kubernetes/virtops/apps/networking/external-dns/external"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  wait: true
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: networking-externaldns-internal
#  namespace: flux-system
#  labels:
#    substitution.flux.home.arpa/enabled: "true"
#spec:
#  dependsOn:
#    - name: cluster-apps-external-secrets-stores
#  path: "./kubernetes/virtops/apps/networking/external-dns/internal"
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: home-ops-kubernetes
#  interval: 30m
#  retryInterval: 1m
#  timeout: 5m
#  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-externaldns-internal-technitium
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
  path: "./kubernetes/virtops/apps/networking/external-dns/internal-technitium"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  wait: false