---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-externaldns-shared
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./kubernetes/virtops/apps/networking/external-dns/shared"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-externaldns-external
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    #- name: cluster-apps-kube-prometheus-stack
  path: "./kubernetes/virtops/apps/networking/external-dns/external"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-externaldns-internal
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    #- name: cluster-apps-kube-prometheus-stack
  path: "./kubernetes/virtops/apps/networking/external-dns/internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  wait: true
---
  apiVersion: kustomize.toolkit.fluxcd.io/v1
  kind: Kustomization
  metadata:
    name: cluster-apps-externaldns-internal-test
    namespace: flux-system
    labels:
      substitution.flux.home.arpa/enabled: "true"
  spec:
    dependsOn:
      - name: cluster-apps-external-secrets-stores
      #- name: cluster-apps-kube-prometheus-stack
    path: "./kubernetes/virtops/apps/networking/external-dns/internal-test"
    prune: true
    sourceRef:
      kind: GitRepository
      name: home-ops-kubernetes
    interval: 30m
    retryInterval: 1m
    timeout: 5m
    wait: true
---
  apiVersion: kustomize.toolkit.fluxcd.io/v1
  kind: Kustomization
  metadata:
    name: cluster-apps-externaldns-internal-new
    namespace: flux-system
    labels:
      substitution.flux.home.arpa/enabled: "true"
  spec:
    dependsOn:
      - name: cluster-apps-external-secrets-stores
      #- name: cluster-apps-kube-prometheus-stack
    path: "./kubernetes/virtops/apps/networking/external-dns/internal-new"
    prune: true
    sourceRef:
      kind: GitRepository
      name: home-ops-kubernetes
    interval: 30m
    retryInterval: 1m
    timeout: 5m
    wait: true