---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bazarr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: bazarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: bazarr # bazarr & postgres-init-db
        INIT_POSTGRES_HOST: postgres-rw.default.svc.cluster.local # bazarr & postgres-init-db
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}" # postgres-init-db
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}" # postgres-init-db
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}" # bazarr & postgres-init-db
        INIT_POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}" # bazarr
  dataFrom:
    - extract:
        key: BAZARR
    - extract:
        key: CLOUDNATIVE_PG
