---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-kube-prometheus-stack
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    #- name: cluster-apps-external-secrets-stores
    - name: cluster-apps-external-secrets
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-thanos
    - name: cluster-apps-alertmanager
  
  path: "./kubernetes/virtops/apps/monitoring/kube-prometheus-stack/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  #wait: true
