---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: pgadmin-secret
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        PGADMIN_DEFAULT_EMAIL: "{{ .ADMIN_EMAIL }}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: ADMIN_USER
    - extract:
        key: CLOUDNATIVE_PG
