---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-loki
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    #- name: cluster-apps-kube-prometheus-stack
    - name: rook-ceph-cluster
    - name: cluster-apps-external-secrets-stores
  path: "./kubernetes/virtops/apps/monitoring/loki/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 20m
