---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-loki
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: monitoring-kube-prometheus-stack
    - name: system-democratic-csi-local-path
    - name: flux-system-external-secrets-stores
  path: "./kubernetes/virtops/apps/monitoring/loki/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 10m
  #retryInterval: 1m
  #timeout: 20m
