---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-outline
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-outline-redis
    #- name: cluster-apps-redis
  path: ./kubernetes/virtops/apps/default/outline/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: outline
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-outline-redis
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-kube-prometheus-stack
  path: ./kubernetes/virtops/apps/default/outline/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: outline-redis
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m