---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-externalsecret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: linkding
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        LD_SUPERUSER_NAME: "{{ .LD_SUPERUSER_NAME }}"
        LD_SUPERUSER_PASSWORD: "{{ .LD_SUPERUSER_PASSWORD }}"
  dataFrom:
    - extract:
        key: LINKDING
