---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./database.yaml
  #- ./helmrelease.yaml
  #- ./externalsecret.yaml
  #- ./pvc.yaml
  # https://icon-sets.iconify.design/simple-icons/drone/

