apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app adminer
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: adminer
      tag: 4.8.1
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/icon: mdi:monitor-screenshot
          hajimari.io/instance: "org"
          external-dns.alpha.kubernetes.io/target: ingress.${ORG_DOMAIN}
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-org-auth@kubernetescrd"
        hosts:
          - host: &host "sql.${ORG_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: tls.adminer
            hosts:
              - *host
    resources:
      requests:
        cpu: 15m
        memory: 105Mi
      limits:
        memory: 105Mi
    env:
      ADMINER_DEFAULT_SERVER: mariadb
