---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: downloads
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
spec:
  storageClassName: downloads
  capacity:
    storage: 1Mi # Size does not matter ...twss
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: pbs.${NET_DOMAIN}
    path: /eros/Downloads
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: downloads
  resources:
    requests:
        storage: 1Mi # Size does not matter ...twss
