---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Grafana
       # GF_DATABASE_USER: "{{ .LOGIN }}"
       # GF_DATABASE_PASSWORD: "{{ .{PASSWORD} }}"
       # GF_DATABASE_HOST: postgres.database.svc.cluster.local:5432
       # GF_DATABASE_NAME: "{{ .{DATABASE_NAME} }}"
       # GF_DATABASE_SSL_MODE: disable
       # GF_DATABASE_TYPE: postgres
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .GF_AUTH_GENERIC_OAUTH_CLIENT_ID }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET }}"
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: "{{ .GF_AUTH_GENERIC_OAUTH_AUTH_URL }}"
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "{{ .GF_AUTH_GENERIC_OAUTH_TOKEN_URL }}"
        GF_AUTH_GENERIC_OAUTH_API_URL: "{{ .GF_AUTH_GENERIC_OAUTH_API_URL }}"
  dataFrom:
    - extract:
        key: GRAFANA
    - extract:
        key: database-grafana-user

