---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-recyclarr
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: media-lidarr
    - name: media-radarr
    - name: media-sonarr
    - name: volsync
  path: ./kubernetes/virtops/apps/media/recyclarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
