---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: thanos-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_BUCKET_NAME: thanos
        S3_BUCKET_HOST: "{{ .s3_host }}"
        S3_BUCKET_REGION: us-east-1
        S3_ACCESS_KEY: "thanos"
        S3_SECRET_KEY: "{{ .minio_thanos_secret_key }}"
  dataFrom:
    - extract:
        key: MINIO
      #rewrite:
      #  - regexp:
      #      source: "(.*)"
      #      target: "minio_$1"
