---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: thanos
      version: 12.13.9
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    existingObjstoreSecret: thanos-s3-secret
    #objstoreConfig:
    #  type: s3
    #  config:
    #    insecure: true
    queryFrontend:
      enabled: true
      ingress:
        enabled: true
        hostname: "thanos.${ORG_DOMAIN}"
        ingressClassName: external
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        tls: true
    query:
      enabled: true
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
      replicaLabels:
        - "__replica__" # must match with kube-prometheus-stack value `.prometheus.prometheusSpec.replicaExternalLabelName`
      resources:
        requests:
          cpu: 15m
          memory: 64M
        # limits:
        #   memory: 99M

    bucketweb:
      enabled: true
      resources:
        requests:
          cpu: 15m
          memory: 64M
        # limits:
        #   memory: 64M

    compactor:
      enabled: true
      extraFlags:
        - "--compact.concurrency"
        - "4"
      retentionResolutionRaw: 14d
      retentionResolution5m: 14d
      retentionResolution1h: 30d
      resources:
        requests:
          cpu: 15m
          memory: 204M
        # limits:
        #   memory: 270M
      persistence:
        enabled: true
        #storageClass: "ceph-block"
        storageClass: "local-hostpath"
        size: 15Gi

    storegateway:
      enabled: true
      resources:
        requests:
          cpu: 23m
          memory: 204M
        # limits:
        #   memory: 226M
      persistence:
        enabled: true
        #storageClass: "ceph-block"
        storageClass: "local-hostpath"
        size: 1Gi

    ruler:
      enabled: true
      alertmanagers:
        #- http://alertmanager.monitoring.svc.cluster.local:9093
        - http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093
      clusterName: virtops # must match with kube-prometheus-stack value `.prometheus.prometheusSpec.externalLabels.cluster`
      config: |-
        groups:
          - name: "PrometheusWatcher"
            rules:
              - alert: "PrometheusDown"
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
      dnsDiscovery:
        enabled: true
      persistence:
        enabled: true
        storageClass: "local-hostpath"
        size: 512Mi
        #storageClass: "ceph-block"
        #size: 1024Mi
      resources:
        requests:
          cpu: 23m
          memory: 128M
        limits:
          memory: 256M

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
