---
# renovate: datasource=github-releases depName=k3s-io/k3s
k3s_release_version: "v1.27.3+k3s1"
k3s_install_hard_links: true
k3s_become: true
k3s_registration_address: 10.28.1.81
k3s_control_node: true
k3s_server:
  node-ip: "{{ ansible_host }}"
  flannel-iface: enp2s0
  tls-san:
    - "{{ k3s_registration_address }}"
    - expanse.{{ NET_DOMAIN }}
  docker: false
  disable-network-policy: true
  disable-cloud-controller: true
  cluster-cidr: "172.30.0.0/16"
  service-cidr: "172.31.0.0/16"
  write-kubeconfig-mode: "0644"
