---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mosquitto
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: mosquitto-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        mosquitto_pwd: |
          {{ .mqtt_username }}:{{ .mqtt_userpass }}
  dataFrom:
    - extract:
        key: MQTT
      