---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shelly-exporter
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: shelly-exporter-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SHELLYPLUG_AUTH_USERNAME: "{{ .SHELLY_USERNAME }}"
        SHELLYPLUG_AUTH_PASSWORD: "{{ .SHELLY_PASSWORD }}"
  dataFrom:
    - extract:
        key: SHELLY
    