---
apiVersion: apps.emqx.io/v2alpha1
kind: EMQX
metadata:
  name: emqx
  namespace: default
spec:
  image: emqx/emqx:5.0.23@sha256:3dec080864623ec12ba8f1ada227949a0cacd1048432febd1e13ca50c6977b05
  # values: https://github.com/emqx/emqx-operator/blob/main/config/samples/emqx/v2alpha1/emqx-full.yaml
  bootstrapConfig: |
    authorization {
      sources = [
        {
          type = built_in_database
          enable = true
        }
      ]

      no_match: "deny"
    }
    dashboard {
      listeners.http {
          bind: 18083
      }
      default_username: "admin"
      default_password: "public"
    }

  coreTemplate:
    metadata:
      name: emqx-core
      labels:
        apps.emqx.io/instance: emqx
        apps.emqx.io/db-role: core
    spec:
      replicas: 3
      volumeClaimTemplates:
        storageClassName: ceph-filesystem
        resources:
          requests:
            storage: 500Mi
        accessModes:
          - ReadWriteMany

      podSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: Always
        supplementalGroups:
          - 100

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - emqx
                topologyKey: kubernetes.io/hostname

  replicantTemplate:
    spec:
      replicas: 0
