---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${ORG_DOMAIN}"
  namespace: networking
spec:
  secretName: "${ORG_DOMAIN}-tls"
  issuerRef:
    # note that I'm using staging below. Fix when deployed
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${ORG_DOMAIN}"
  dnsNames:
    - "${ORG_DOMAIN}"
    - "*.${ORG_DOMAIN}"
