---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-emqx-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-external-secrets-stores
  path: ./kubernetes/virtops/apps/default/emqx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  #healthChecks:
  #  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
  #    kind: HelmRelease
  #    name: emqx-operator
  #    namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-emqx-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-emqx-operator
  path: ./kubernetes/virtops/apps/default/emqx/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  #healthChecks:
  #  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
  #    kind: HelmRelease
  #    name: emqx-operator
  #    namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m