---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-secrets
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: esphome-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secrets.yaml: |-
          wifi_ssid: "{{ .wifi_ssid }}"
          wifi_password: "{{ .wifi_password }}"

          mqtt_host: "{{ .mqtt_host }}"
          mqtt_user: "mqtt"
          mqtt_password: "{{ .mqtt_password }}"

          domain_devices: "{{ .esphome_net_domain }}"
  dataFrom:
    - extract:
        key: ESPHOME
      #rewrite:
      #  - regexp:
      #      source: "(.*)"
      #      target: "esphome_$1"
    #- extract:
    #    key: mosquitto
    #  rewrite:
    #    - regexp:
    #        source: "(.*)"
    #        target: "mosquitto_$1"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-deploykey
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: esphome-deploykey
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ESPHOME
    - find:
        path: id_
#  data:
#    - secretKey: id_ed25519
#      remoteRef:
#        key: esphome
#        property: github_deploy_key
