---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-secrets
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: esphome-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secrets.yaml: |-
          wifi_ssid: "{{ .esphome_wifi_ssid }}"
          wifi_pwd: "{{ .esphome_wifi_password }}"

          mqtt_host: "{{ .esphome_mqtt_host }}"
          mqtt_user: "mqtt"
          mqtt_pwd: "{{ .esphome_mqtt_password }}"

          domain_devices: "{{ .esphome_net_domain }}"
  dataFrom:
    - extract:
        key: esphome
      rewrite:
        - regexp:
            source: "(.*)"
            target: "esphome_$1"
    - extract:
        key: mosquitto
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mosquitto_$1"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-deploykey
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: esphome-deploykey
    creationPolicy: Owner
  data:
    - secretKey: id_ed25519
      remoteRef:
        key: esphome
        property: github_deploy_key
