---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-deploykey
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: esphome-deploykey
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ESPHOME
    - find:
        path: id_
---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: &name esphome-secrets
  namespace: monitoring
spec:
  provider:
    doppler:
      project: esphome
      config: prd
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth-api
            key: DOPPLER_TOKEN
            namespace: flux-system
      format: yaml
---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name esphome-secrets
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: *name
  target:
    name: *name

  dataFrom:
    - find:
        path: DOPPLER_SECRETS_FILE
      rewrite:
        - regexp:
            source: "DOPPLER_SECRETS_FILE"
            target: "secrets.yaml"

