---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: statefulset

    image:
      repository: ghcr.io/esphome/esphome
      tag: 2023.8.2@sha256:b0da16a8b58bb1a2fd94cc2377c0a2ab6625fb034af8981b721743205a3307f0
    
    env: 
      TZ: ${TIMEZONE}
      ESPHOME_DASHBOARD_USE_PING: true

    podAnnotations:
      secret.reloader.stakater.com/reload: esphome-secrets,esphome-deploykey
      #k8s.v1.cni.cncf.io/networks: macvlan-static-iot-esphome

    service:
      main:
        ports:
          http:
            port: 6052

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
          - host: &host "esphome.${ORG_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      secrets:
        enabled: true
        type: secret
        name: esphome-secrets
        mountPath: /config/secrets.yaml
        subPath: secrets.yaml
      esphome-cache:
        enabled: true
        type: emptyDir
        mountPath: /config/.esphome
      esphome-config:
        enabled: true
        type: emptyDir
        mountPath: /esphome-config
      deploy-key:
        enabled: true
        type: secret
        name: esphome-deploykey
        defaultMode: 256
        subPath:
          - path: id_ed25519
          #- path: deploy_key
            mountPath: /root/.ssh/id_ed25519

    resources:
      requests:
        cpu: 300m
        memory: 512M
      limits:
        memory: 2048M

    #sidecars:
    #  subcleaner:
    #    image: registry.k8s.io/git-sync/git-sync:v4.0.0@sha256:ad48c2dd8f5ae73e783c4a55bedb4cc13d51d347d157e6564c4debfd0fbd429d
    #    imagePullPolicy: IfNotPresent
    #    args:
    #      - --repo=https://github.com/fisherbln/esphome-config
    #      - --branch=main
    #      - --wait=86400 # 1 day
    #      - --root=/esphome-config
    #    volumeMounts:
    #      - { name: esphome-config, mountPath: /esphome-config }


    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteMany
        size: 1Gi
        storageClass: ceph-filesystem
