---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./config
  - ./pvc.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  #- ./replicationsource.yaml
commonLabels:
  app.kubernetes.io/name: esphome
  app.kubernetes.io/instance: esphome
  app.kubernetes.io/managed-by: fluxcd.io
