apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler-virtops
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-secret
            key: dopplerVirtOpsToken
            namespace: flux-system
