---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: doppler-token-auth-api
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: doppler-token-auth-api
    creationPolicy: Owner
  dataFrom:
    #- extract:
    #    key: DOPPLER_TOKEN
    - find:
        path: DOPPLER_TOKEN
        
