---
apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
commonLabels:
  app.kubernetes.io/name: paperless
  app.kubernetes.io/instance: paperless
