---
ingress:
  - hostname: "${ORG_DOMAIN}"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: external.${ORG_DOMAIN}
  - hostname: "*.${ORG_DOMAIN}"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: external.${ORG_DOMAIN}
  - service: http_status:404
