---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zalando-postgres-cluster
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: postgres.postgres.credentials.postgresql.acid.zalan.do
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: ZOLANDO_POSTGRES
        property: POSTGRES_SUPER_USER
    - secretKey: password
      remoteRef:
        key: ZOLANDO_POSTGRES
        property: POSTGRES_SUPER_PASS
