---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zalando-postgres-cluster
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: postgres.postgres.credentials.postgresql.acid.zalan.do
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: ZOLANDO_POSTGRES
    