---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: semaphore
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      # https://github.com/ansible-semaphore/semaphore/issues/1149
      repository: ghcr.io/onedr0p/semaphore
      tag: v2.9.2@sha256:2787e84a4b7a294913ab46c2fc2c7221fa44a49f4954a91db6a99e89a42798bb
    env:
      SEMAPHORE_LDAP_ACTIVATED: "no"
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_EMAIL: admin@${ORG_DOMAIN}
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB:
        valueFrom:
          secretKeyRef:
            name: &db_secret database-semaphore-user
            key: DATABASE_NAME
      SEMAPHORE_DB_USER:
        valueFrom:
          secretKeyRef:
            name: *db_secret
            key: LOGIN
      SEMAPHORE_DB_PASS:
        valueFrom:
          secretKeyRef:
            name: *db_secret
            key: PASSWORD
      SEMAPHORE_DB_HOST:
        valueFrom:
          secretKeyRef:
            name: *db_secret
            key: HOST
      SEMAPHORE_DB_PORT:
        value: 5432
    envFrom:
      - secretRef:
          name: semaphore-secret
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:ansible
        hosts:
          - host: &host "{{ .Release.Name }}.${ORG_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    