---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: default-glauth
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system-external-secrets-stores
  path: ./kubernetes/virtops/apps/default/glauth/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
