---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap
  namespace: auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: lldap-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # lldap
        LLDAP_JWT_SECRET: "{{ .LLDAP_JWT_SECRET }}"
        LLDAP_LDAP_USER_PASS: "{{ .LLDAP_LDAP_USER_PASS }}"
        LLDAP_USER_DN: "{{ .LLDAP_USER_DN }}"
        LLDAP_LDAP_USER_EMAIL: "{{ .LLDAP_LDAP_USER_EMAIL }}"
        LLDAP_SERVER_KEY_SEED: "{{ .LLDAP_SERVER_KEY_SEED }}"
        #LLDAP_DATABASE_URL: "postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-rw.default.svc.cluster.local/lldap"
        LLDAP_SMTP_OPTIONS__SERVER: "{{ .AUTHELIA_NOTIFIER_SMTP_HOST }}"
        LLDAP_SMTP_OPTIONS__PORT: "587"
        LLDAP_SMTP_OPTIONS__FROM: "{{ .AUTHELIA_NOTIFIER_SMTP_USERNAME }}"
        LLDAP_SMTP_OPTIONS__USER: "{{ .AUTHELIA_NOTIFIER_SMTP_USERNAME }}"
        LLDAP_SMTP_OPTIONS__PASSWORD: "{{ .AUTHELIA_NOTIFIER_SMTP_PASSWORD }}"
        # Postgres Init
        #INIT_POSTGRES_DBNAME: lldap
        #INIT_POSTGRES_HOST: postgres-rw.default.svc.cluster.local
        #INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        #INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        #INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"

  dataFrom:
    - extract:
        key: LLDAP
    #- extract:
    #    key: CLOUDNATIVE_PG
    - extract:
        key: AUTHELIA
