---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: compreface-db
  namespace: default
spec:
  database: compreface
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: compreface-user
  namespace: default
spec:
  role: compreface
  database: compreface-db
  secretName: database
  privileges: OWNER
