---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./database.yaml
  #- ./helmrelease.yaml
  - ./postgresCluster.yaml
  #- ./volsync.yaml
  #- ./gatus.yaml
