---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./authelia.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  #- ./cloudnative-pg.yaml
  - ./crunchydata.yaml
  - ./democratic-csi.yaml
  - ./emqx.yaml
  - ./ext-postgres-operator.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./fairwinds.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./kubernetes-sigs-descheduler.yaml
  - ./kubernetes-sigs-metrics-server.yaml
  - ./kubernetes-sigs-nfd.yaml
  - ./kyverno.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./tf-controller.yaml
  - ./vector.yaml
  - ./weave-gitops.yaml
  - ./zalando-postgres-operator.yaml
