---
- hosts:
    - klipper
  gather_facts: false
  any_errors_fatal: true
  become: false

  pre_tasks:
    - name: Gathering facts
      ansible.builtin.gather_facts:
      become: true
      tags:
        - always

  tasks:
    - name: "role: linux.common.os"
      ansible.builtin.import_role:
        name: linux.common.os
      tags:
        - common
        - os

    - name: "role: klipper.os"
      ansible.builtin.import_role:
        name: klipper.os
      tags:
        - klipper
        - os

    - name: "role: klipper.apps"
      ansible.builtin.import_role:
        name: klipper.apps
      tags:
        - klipper
        - apps
