apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler-global
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-secret
            key: dopplerToken
            namespace: vault
