---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-external-secrets
  namespace: flux-system
spec:
  path: ./kubernetes/virtops/apps/kube-system/external-secrets/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: external-secrets
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-external-secrets-stores
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets
  path: ./kubernetes/virtops/apps/kube-system/external-secrets/stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: clustersecretstores.external-secrets.io
      #kind: HelmRelease
      name: doppler-virtops
      #name: external-secrets-stores
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
