---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: outline-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Outline
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        SECRET_KEY: "{{ .SECRET_KEY }}"
        UTILS_SECRET: "{{ .UTILS_SECRET }}"
        DATABASE_URL: postgres://{{ .postgres_user }}:{{ .postgres_pass }}@postgres-rw.default.svc.cluster.local:5432/outline
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        # Postgres Init
        POSTGRES_DB: outline
        POSTGRES_HOST: postgres-rw.default.svc.cluster.local
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PASS: "{{ .postgres_pass }}"
        POSTGRES_USER: "{{ .postgres_user }}"
  dataFrom:
    - extract:
        key: OUTLINE
    - extract:
        key: CLOUDNATIVE_PG
