---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-paperless-redis
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-kube-prometheus-stack
  path: "./kubernetes/virtops/apps/default/paperless/redis"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  #healthChecks:
  #  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
  #    kind: HelmRelease
  #    name: paperless-redis
  #    namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-paperless
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-paperless-redis
  interval: 10m
  path: "./kubernetes/virtops/apps/default/paperless/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  #healthChecks:
  #  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
  #    kind: HelmRelease
  #    name: paperless
  #    namespace: default
  retryInterval: 1m
  timeout: 3m
  wait: true
  
