---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: default-paperless-redis
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-rook-ceph-cluster
    #- name: cluster-apps-kube-prometheus-stack
  path: "./kubernetes/virtops/apps/default/paperless/redis"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: default-paperless
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: default-paperless-redis
  interval: 10m
  path: "./kubernetes/virtops/apps/default/paperless/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  retryInterval: 1m
  timeout: 5m
  wait: true
  
