---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./adminer/ks.yaml
  #- ./cloudnative-pg/ks.yaml
  - ./esphome/ks.yaml
  - ./glauth/ks.yaml
  - ./immich/ks.yaml
  #- ./influxdb/ks.yaml
  - ./linkding/ks.yaml
  - ./mosquitto/ks.yaml
  - ./node-red/ks.yaml
  - ./outline/ks.yaml
  - ./paperless/ks.yaml
  - ./pgadmin/ks.yaml
  - ./redis/ks.yaml
  - ./scrypted/ks.yaml
  #- ./smtp-relay/ks.yaml
  - ./vnc/ks.yaml
  