---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-csi-addons-controller-manager
  namespace: flux-system
spec:
  path: ./deploy/controller
  sourceRef:
    kind: GitRepository
    name: kubernetes-csi-addons
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  path: ./kubernetes/virtops/apps/rook-ceph/rook-ceph/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: rook-ceph
  path: ./kubernetes/virtops/apps/rook-ceph/rook-ceph/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: rook-ceph-cluster-monitoring
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: rook-ceph
#  path: ./kubernetes/virtops/apps/rook-ceph/rook-ceph/monitoring
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: home-ops-kubernetes
#  interval: 30m
#  retryInterval: 1m
#  timeout: 5m
