---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./nextdns-exporter/ks.yaml
  - ./node-exporter/ks.yaml
  - ./loki/ks.yaml
  #- ./shelly-exporter/ks.yaml
  #- ./snmp-exporter/ks.yaml
  - ./thanos/ks.yaml
  - ./vector/ks.yaml
  # Standard Resources
  #- ./miscellaneous