---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
resources:
  - ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: terraform-registry
  app.kubernetes.io/instance: terraform-registry
