#!/usr/bin/env bash
rm -rf ./cni/charts
echo "# This manifest was generated by automation. DO NOT EDIT." > ./cilium.yaml
kustomize build \
  --enable-helm \
  --load-restrictor=LoadRestrictionsNone \
  . \
  >> ./cni/cilium.yaml
rm -rf ./cni/charts
