---
#cluster:
#  id: 1
#  name: virtops
autoDirectNodeRoutes: true
bgp:
  announce:
    loadbalancerIP: true
  enabled: false
containerRuntime:
  integration: containerd
endpointRoutes:
  enabled: true
hubble:
  enabled: false
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 172.28.0.0/16
k8sServiceHost: 10.5.0.10
k8sServicePort: 6443
kubeProxyReplacement: strict
loadBalancer:
  algorithm: maglev
  mode: dsr
localRedirectPolicy: true
operator:
  rollOutPods: true
rollOutCiliumPods: true
securityContext:
  privileged: true
tunnel: disabled
