---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-grafana
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    #- name: cluster-apps-cloudnative-pg
    #- name: cluster-apps-external-secrets-stores
    - name: cluster-apps-external-secrets
    - name: cluster-apps-kube-prometheus-stack
  interval: 10m
  path: "./kubernetes/virtops/apps/monitoring/grafana/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  retryInterval: 1m
  timeout: 3m

