---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: sonarr-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # PUSHOVER_TOKEN, SONARR__API_KEY
        key: SONARR
    - extract:
        # pushover_api_arrApp_key
        key: PUSHOVER
