---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: sonarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SONARR__API_KEY: "{{ .SONARR__API_KEY }}"
        SONARR__POSTGRES_HOST: &dbhost postgres-rw.default.svc.cluster.local
        SONARR__POSTGRES_MAIN_DB: &dbname sonarr-main
        SONARR__POSTGRES_LOG_DB: sonarr-log
        SONARR__POSTGRES_PASSWORD: "{{ .SONARR_POSTGRES_PASSWORD }}"
        SONARR__POSTGRES_USER: "{{ .SONARR_POSTGRES_USERNAME }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_PASS: "{{ .SONARR_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: "{{ .SONARR_POSTGRES_USERNAME }}"
  dataFrom:
    - extract:
        # SONARR__API_KEY
        key: SONARR
    - extract:
        # PUSHOVER_STARR_APIKEY
        key: PUSHOVER
    - extract:
        key: CLOUDNATIVE_PG