---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: &name sonarr
  namespace: monitoring
spec:
  provider:
    doppler:
      project: *name
      config: prd
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth-api
            key: DOPPLER_TOKEN
            namespace: flux-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name sonarr
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: *name
  target:
    name: sonarr-secret
    template:
      engineVersion: v2
      data:
        SONARR__API_KEY: "{{ .SONARR__API_KEY }}"
  dataFrom:
    - find:
        name:
          regexp: .*
      rewrite:
        - regexp:
            source: "(.*)"
            target: "$1"
