---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nextdns-exporter-trusted
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: 'true'
spec:
  path: './kubernetes/virtops/apps/monitoring/nextdns-exporter/trusted/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  dependsOn:
    - name: cluster-apps-external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nextdns-exporter-iot
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: 'true'
spec:
  path: './kubernetes/virtops/apps/monitoring/nextdns-exporter/iot/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  dependsOn:
    - name: cluster-apps-external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nextdns-exporter-servers
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: 'true'
spec:
  path: './kubernetes/virtops/apps/monitoring/nextdns-exporter/servers/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  dependsOn:
    - name: cluster-apps-external-secrets