---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: github-token-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: FLUX
  #data:
  #  - secretKey: token
  #    remoteRef:
  #      key: flux
  #      property: github_token
