---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: &name nextdns-exporter-iot
  namespace: monitoring
spec:
  provider:
    doppler:
      project: nextdns-exporter
      config: prd
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth-api
            key: DOPPLER_TOKEN
            namespace: flux-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name nextdns-exporter-iot
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: *name
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        NEXTDNS_API_KEY: "{{ .NEXTDNS_API_KEY }}"
        NEXTDNS_PROFILE: "{{ .NEXTDNS_PROFILE_IOT }}"
  # NEXTDNS_API_KEY, NEXTDNS_PROFILE
  dataFrom:
    - find:
        name:
          regexp: .*
      rewrite:
        - regexp:
            source: "(.*)"
            target: "$1"
