---
all:
  children:
    linux:
      children:
        klipper:
        pikvm:
        roomassistant:

    storage:
      hosts:
        nas:

    klipper:
      hosts:
        horus:

    pikvm:
      hosts:
        diego:
