---
all:
  children:
    linux:
      children:
        klipper:
        pikvm:
        proxmox:

    storage:
      hosts:
        nas:

    klipper:
      hosts:
        horus:

    pikvm:
      hosts:
        diego:
    proxmox:
      hosts:
        pve1:
          ansible_host: 10.28.1.51
        pve2:
          ansible_host: 10.28.1.52
        pve3:
          ansible_host: 10.28.1.53
        pbs:
          ansible_host: 10.28.1.54
