---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: node-red-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: node-red-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: NODE_RED
