---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app node-red
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: docker.io/nodered/node-red
      tag: 3.0.2

    envFrom:
      - secretRef:
          name: node-red-secrets
    env:
      TZ: ${TIMEZONE}
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"

    service:
      main:
        ports:
          http:
            port: 1880

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          #hajimari.io/appName: "Node-RED"
          #hajimari.io/instance: "org"
          #hajimari.io/enable: "true"
          #hajimari.io/icon: "graph-outline"
          external-dns.alpha.kubernetes.io/target: ipv4.${ORG_DOMAIN}
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
          - host: &host "node-red.${ORG_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: node-red-config-v1
        mountPath: /data

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"

    resources:
      requests:
        cpu: 15m
        memory: 127M
      limits:
        memory: 200M
