---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externaldns-internal
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: externaldns-internal-secrets
    creationPolicy: Owner
  dataFrom:
  # bind_rndc_algorithm, bind_rndc_secret
    - extract:
        key: BIND
  #data:
  #  - secretKey: bind_rndc_algorithm
  #    remoteRef:
  #      key: BIND
  #      property: externaldns_algorithm
  #  - secretKey: bind_rndc_secret
  #    remoteRef:
  #      key: BIND
  #      property: externaldns_secret
