---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lidarr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: lidarr-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # LIDARR__API_KEY
        key: LIDARR
