---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: 3.0.5
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 30m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    crds:
      install: true

    replicaCount: 3

    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1

    grafana:
      enabled: true
      annotations:
        grafana_folder: Kyverno
      
    backgroundController:
      serviceMonitor:
        enabled: true

      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - create
                - update
                - patch
                - delete
                - get
                - list

    cleanupController:
      serviceMonitor:
        enabled: true
        interval: 1m
    reportsController:
      serviceMonitor:
        enabled: true
        interval: 1m
    
    admissionController:
      replicas: 3

      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - create
                - update
                - delete

      serviceMonitor:
        enabled: true
        interval: 1m
        
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: kyverno
