---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: externaldns
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.12.2
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-external-dns
        namespace: flux-system
      interval: 30m

  values:
    domainFilters:
      - ${XYZ_DOMAIN}

    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: externaldns-secrets
            key: api_token

    extraArgs:
      - --cloudflare-proxied
      - --annotation-filter=external-dns.alpha.kubernetes.io/target

    podAnnotations:
      secret.reloader.stakater.com/reload: externaldns-secrets

    policy: sync
    provider: cloudflare

    serviceMonitor:
      enabled: true

    sources:
      - ingress

    txtPrefix: "k8s."
