---
- name: Add packages on Debian/Ubuntu machines
  become: true
  when:
    - ansible_os_family == 'Debian'
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - git
      - android-tools-adb
