---
- name: Manage openssh keypair
  community.crypto.openssh_keypair:
    type: ed25519
    path: /home/{{ansible_user}}/.ssh/id_ed25519

- name: Add openssh keypair to SSH config
  ansible.builtin.blockinfile:
    path: /home/{{ansible_user}}/.ssh/config
    mode: 0600
    create: true
    block: |
      IdentityFile ~/.ssh/id_ed25519
