---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app emqx-operator
  namespace: default
spec:
  interval: 60m
  chart:
    spec:
<<<<<<< HEAD
      chart: emqx
      version: 5.0.22
=======
      chart: *app
      version: 2.1.1
>>>>>>> fb8079b (try enabling emqx operator)
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
      interval: 60m
  # Values link: https://github.com/emqx/emqx-operator/blob/main/deploy/charts/emqx-operator/values.yaml
  values:
    skipCRDs: false

    replicaCount: 1

    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 30Mi
  