---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-emqx-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-kube-prometheus-stack
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-external-secrets-stores
  path: ./kubernetes/virtops/apps/default/emqx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-emqx-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-emqx-operator
  path: ./kubernetes/virtops/apps/default/emqx/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 5m