---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-server
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: immich-typesense
  values:
    controller:
      replicas: 2
      strategy: RollingUpdate
      annotations:
        configmap.reloader.stakater.com/reload: &configmap immich-configmap
        secret.reloader.stakater.com/reload: &secret immich-secret
    image:
      repository: ghcr.io/immich-app/immich-server
      tag: v1.74.0@sha256:6b5a532b67d0a12276062dc404499a7b0e9fc90225e3e58199554fb776329e76
    command: /bin/sh
    args:
      - ./start-server.sh
    env:
      DB_HOSTNAME:
        valueFrom:
          secretKeyRef:
            name: database-immich-user
            key: HOST
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: database-immich-user
            key: LOGIN
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: database-immich-user
            key: PASSWORD
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: database-immich-user
            key: DATABASE_NAME
    envFrom:
      - secretRef:
          name: immich-secret
      - configMapRef:
          name: immich-configmap
    service:
      main:
        ports:
          http:
            port: 3001
    persistence:
      library:
        enabled: true
        existingClaim: immich-nfs
        mountPath: /usr/src/app/upload
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
