---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-add-ons
  namespace: flux-system
spec:
  path: ./kubernetes/virtops/apps/flux-system/addons
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  dependsOn:
    - name: cluster-apps-external-secrets-stores
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
