---
ansible_host: "10.1.1.11"
ansible_python_interpreter: /volume1/@appstore/python310/bin/python3

certificates:
  - common_name: "*.nickeson.xyz"
    email: "postmaster@nickeson.xyz"

apps:
  syno_cli:
    # renovate: docker-image
    image: ghcr.io/reddec/syno-cli:0.1.2
    data_folder: /volume1/docker/syno_cli

  autoscan:
    # renovate: docker-image
    image: cloudb0x/autoscan:1.3.0
    data_folder: /volume1/docker/autoscan

  garage:
    # renovate: docker-image
    image: dxflrs/garage:v0.8.2
    config_folder: /volume1/docker/garage
    data_folder: /volume1/docker/garage/data
    meta_folder: /volume1/docker/garage/meta
