---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-prowlarr
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system-external-secrets-stores
    - name: rook-ceph-cluster
    - name: volsync
  path: ./kubernetes/virtops/apps/media/prowlarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
