---
apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: networking
  labels:
    app.kubernetes.io/name: unifi
    app.kubernetes.io/instance: unifi
spec:
  type: ExternalName
  externalName: unifi.${NET_DOMAIN}
  ports:
    - name: http
      port: &port 8443
      protocol: TCP
      targetPort: *port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi
  namespace: networking
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
  labels:
    app.kubernetes.io/name: unifi
    app.kubernetes.io/instance: unifi
spec:
  ingressClassName: external
  rules:
    - host: &host unifi.${ORG_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unifi
                port:
                  number: 8443
  tls:
    - hosts:
        - *host
