---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vector-geoipupdate
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: vector-geoipupdate
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: MAXMIND
        