---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: gatus-db
  namespace: monitoring
spec:
  database: gatus
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: gatus-user
  namespace: monitoring
spec:
  role: gatus
  database: gatus-db
  secretName: database
  privileges: OWNER
