---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-zalando-postgres
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/virtops/apps/database/zalando-postgres/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  dependsOn:
    - name: rook-ceph-cluster
    - name: cluster-apps-external-secrets-stores
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-zalando-postgres-cluster
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/virtops/apps/database/zalando-postgres/cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-zalando-postgres
    - name: rook-ceph-cluster
    - name: cluster-apps-external-secrets-stores
