---
    apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: alertmanager
      namespace: monitoring
    spec:
      secretStoreRef:
        kind: ClusterSecretStore
        name: doppler-virtops
  target:
    name: alertmanager-secret
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: alertmanager-config-tpl
            items:
              - key: alertmanager.yaml
  dataFrom:
    #- extract:
    #    key: pushover
    - extract:
        key: ALERTMANAGER