---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-gatus-ep
  namespace: monitoring
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: alertmanager
        group: guarded
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: alertmanager.${ORG_DOMAIN}
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: pushover
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-gatus-ep
  namespace: monitoring
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: prometheus
        group: guarded
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: prometheus.${ORG_DOMAIN}
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: pushover
