---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database-crunchy-postgres-operator
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/virtops/apps/database/crunchy-postgres-operator/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
