---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: cloudflared-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials.json: |
          {
            "AccountTag": "{{ .account-tag }}",
            "TunnelSecret": "{{ .tunnel-secret }}",
            "TunnelID": "${CLUSTER_CLOUDFLARE_TUNNEL_ID}"
          }
  dataFrom:
    - extract:
        key: CLOUDFLARE
      
