---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-redis
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    global:
      nameOverride: *app
    image:
      repository: public.ecr.aws/docker/library/redis
      tag: 7.0.12@sha256:723a3268e4ee04f55ce667cd379113e21a03272092c868442f5a20bb2445c08b

    service:
      main:
        ports:
          http:
            enabled: false
          redis:
            enabled: true
            port: 6379

    resources:
      requests:
        cpu: 23m
        memory: 64M
      limits:
        memory: 64M
