---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grocy
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: grocy-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # lldap
        GROCY_LDAP_BIND_PW: "{{ .LLDAP_SERVER_KEY_SEED }}"

  dataFrom:
    - extract:
        key: LLDAP

