---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grocy
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: linuxserver/grocy
      tag: 4.0.3@sha256:a1c47bd7b7f8d324f9e6c26cde8c7e0441be0eccdef3a2bb4641bd9f640a0539
    env:
      TZ: "${TIMEZONE}"
      GROCY_MODE: "production"
      GROCY_CULTURE: "en_US"
      GROCY_CURRENCY: "USD"
      GROCY_AUTH_CLASS: Grocy\Middleware\ReverseProxyAuthMiddleware
      PUID: "1000"
      PGID: "1000"
      # See here for env vars: https://github.com/grocy/grocy/blob/master/config-dist.php
      #GROCY_REVERSE_PROXY_AUTH_HEADER: HTTP_REMOTE_USER
      GROCY_REVERSE_PROXY_AUTH_HEADER: REMOTE_USER
      GROCY_REVERSE_PROXY_USE_ENV: false
      #GROCY_LDAP_ADDRESS: ldap://lldap.auth.svc.cluster.local:389
      #GROCY_LDAP_BASE_DN: dc=home,dc=arpa
      #GROCY_LDAP_BIND_DN: uid=admin,ou=people,dc=home,dc=arpa
      #GROCY_LDAP_BIND_PW: #pushed from envFrom vars
      #GROCY_LDAP_USER_FILTER: "(OU=grocy_users)"
      #GROCY_LDAP_UID_ATTR: uid
    #envFrom:
    #  - secretRef:
    #      name: "grocy-secret"

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.${ORG_DOMAIN}
          nginx.ingress.kubernetes.io/auth-method: GET
          nginx.ingress.kubernetes.io/auth-url: http://authelia.auth.svc.cluster.local/api/verify
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${ORG_DOMAIN}?rm=$request_method
          nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
          nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Method $request_method;
        hosts:
          - host: &host "grocy.${ORG_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: ceph-block
    persistence:
      viewcache:
        enabled: true
        type: emptyDir
        mountPath: /config/data/viewcache
    