{
  authorization {
    sources = [
      {
        type = built_in_database
        enable = true
      }
    ]

    no_match: "deny"
  }
  dashboard {
    listeners.http {
        bind: 18083
    }
    default_username: "admin"
    default_password: ${mqtt_admin_pass}
  }
}
