---
clusterName: virtops

talosVersion: v1.3.6
kubernetesVersion: 1.26.1
endpoint: "https://virtops.nickeson.net:6443"

cniConfig:
  name: none

additionalApiServerCertSans:
  - ${clusterEndpointIP}

additionalMachineCertSans:
  - ${clusterEndpointIP}
  - virtops.nickeson.net

nodes:
  - hostname: delta.nickeson.net
    disableSearchDomain: true
    ipAddress: 10.28.28.71
    controlPlane: true
    installDisk: /dev/sda
    #networkInterfaces:
    #  - interface: eth0
    #    dhcp: true
    #    vlans:
    #      - vlanId: 20
    #        dhcp: false
    #        addresses:
    #          - 10.1.3.141/24
  - hostname: enigma.nickeson.net
    disableSearchDomain: true
    ipAddress: 10.28.28.72
    controlPlane: true
    installDisk: /dev/sda
    #networkInterfaces:
    #  - interface: eth0
    #    dhcp: true
    #    vlans:
    #      - vlanId: 20
    #        dhcp: false
    #        addresses:
    #          - 10.1.3.142/24
  - hostname: felix.nickeson.net
    disableSearchDomain: true
    ipAddress: 10.28.28.73
    controlPlane: true
    installDisk: /dev/sda
   #networkInterfaces:
   #   - interface: eth0
   #     dhcp: true
   #     vlans:
   #       - vlanId: 20
   #         dhcp: false
   #         addresses:
   #           - 10.1.3.143/24

controlPlane:
  patches:
    - |-
      cluster:
        allowSchedulingOnMasters: true
        apiServer:
        controllerManager:
        discovery:
          registries:
            service:
              disabled: true
        proxy:
          disabled: true
        scheduler:

      machine:
        files:
          - content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
            path: /etc/cri/conf.d/20-customization.part
            op: create
        kubelet:
          extraArgs:
            feature-gates: GracefulNodeShutdown=true
            #rotate-server-certificates: "false"
            rotate-server-certificates: "true"
        install:
          extraKernelArgs:
            - "talos.logging.kernel=udp://vector.nickeson.net:6050/"
        logging:
          destinations:
            - endpoint: "udp://vector.nickeson.net:6051/"
              format: json_lines
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - virtops.nickeson.net
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: false
          servers:
            - 10.28.1.1

    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl
