---
clusterName: virtops

talosVersion: v1.4.4
kubernetesVersion: 1.27.1
endpoint: "https://virtops.${net_domain}:6443"
clusterPodNets:
  - 172.22.0.0/16
clusterSvcNets:
  - 172.24.0.0/14

cniConfig:
  name: none

additionalApiServerCertSans:
  - ${clusterEndpointIP}

additionalMachineCertSans:
  - ${clusterEndpointIP}
  - virtops.${net_domain}

nodes:
  - hostname: delta.${net_domain}
    disableSearchDomain: true
    ipAddress: 10.28.28.71
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
    #  - interface: eth1
    #    dhcp: true
    #    vlans:
    #      - vlanId: 20
    #        dhcp: false
    #        addresses:
    #          - 10.1.3.141/24
  - hostname: enigma.${net_domain}
    disableSearchDomain: true
    ipAddress: 10.28.28.72
    controlPlane: true
    installDisk: /dev/sda
    #networkInterfaces:
    #  - interface: eth1
    #    dhcp: true
  - hostname: felix.${net_domain}
    disableSearchDomain: true
    ipAddress: 10.28.28.73
    controlPlane: true
    installDisk: /dev/sda
   #networkInterfaces:
   #   - interface: eth1
   #     dhcp: true
  - hostname: node-pve1.${net_domain}
    disableSearchDomain: true
    ipAddress: 10.28.28.61
    controlPlane: false
    installDisk: /dev/sda
    #networkInterfaces:
    #   - interface: eth1
    #     dhcp: true
  - hostname: node-pve2.${net_domain}
    disableSearchDomain: true
    ipAddress: 10.28.28.62
    controlPlane: false
    installDisk: /dev/sda
    #networkInterfaces:
    #   - interface: eth1
    #     dhcp: true
  - hostname: node-pve3.${net_domain}
    disableSearchDomain: true
    ipAddress: 10.28.28.63
    controlPlane: false
    installDisk: /dev/sda
    #networkInterfaces:
    #   - interface: eth1
    #     dhcp: true

controlPlane:
  patches:
    - |-
      cluster:
        allowSchedulingOnMasters: true
        proxy:
          disabled: true
        extraManifests:
          - https://raw.githubusercontent.com/fisherbln/virt-ops/main/infrastructure/talos/virtops/cni/cilium.yaml
          - https://raw.githubusercontent.com/fisherbln/virt-ops/main/infrastructure/talos/virtops/kubelet-csr-approver/kubelet-csr-approver.yaml

    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    - |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
        kubelet:
          extraArgs:
            feature-gates: CronJobTimeZone=true,GracefulNodeShutdown=true,NewVolumeManagerReconstruction=false
            rotate-server-certificates: "true"
          extraConfig:
            maxPods: 150
          nodeIP:
            validSubnets:
                - 10.28.28.0/24
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - ${clusterName}.bjw-s.tech
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: false
          servers:
            - 10.28.1.1

worker:
  patches:
    - |-
      cluster:
        allowSchedulingOnMasters: false
        apiServer:
        controllerManager:
        discovery:
          registries:
            service:
              disabled: true
        proxy:
          disabled: true
        scheduler:

      machine:
        files:
          - content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
            path: /etc/cri/conf.d/20-customization.part
            op: create
        kubelet:
          extraArgs:
            feature-gates: GracefulNodeShutdown=true
            #rotate-server-certificates: "false"
            rotate-server-certificates: "true"
        install:
          extraKernelArgs:
            - "talos.logging.kernel=udp://vector.${net_domain}:6050/"
        logging:
          destinations:
            - endpoint: "udp://vector.${net_domain}:6051/"
              format: json_lines
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - virtops.${net_domain}
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: false
          servers:
            - 10.28.1.1
