---
- name: Manage config from git
  block:
    - name: Manage repository folder
      ansible.builtin.file:
        path: "{{klipper_config_repo_destination}}"
        state: directory
        mode: 0775

    - name: Checkout {{klipper_config_repo}}
      ansible.builtin.git:
        repo: "{{ klipper_config_repo }}"
        dest: "{{ klipper_config_repo_destination }}"
        accept_newhostkey: true
      ignore_errors: true

    - name: Symlink configuration folder
      ansible.builtin.file:
        state: link
        force: true
        src: "{{ klipper_config_repo_destination}}/{{klipper_config_repo_subfolder | default ('') }}"
        dest: "{{ klipper_config_folder }}"
  when:
    - klipper_config_repo is defined
    - klipper_config_repo != None
    - klipper_config_repo | length > 0

- name: Check if moonraker secrets exist
  ansible.builtin.stat:
    path: "{{ moonraker_secrets_file }}"
  register: var_moonrakersecrets

- name: Create moonraker secrets file
  ansible.builtin.copy:
    dest: "{{ moonraker_secrets_file }}"
    content: |
      [mqtt_credentials]
      username: {{ moonraker_mqtt_username }}
      password: {{ moonraker_mqtt_password }}
    mode: 0600
  when:
    - not var_moonrakersecrets.stat.exists
    - moonraker_mqtt_username is defined
    - moonraker_mqtt_username != None
    - moonraker_mqtt_username | length > 0
    - moonraker_mqtt_password is defined
    - moonraker_mqtt_password != None
    - moonraker_mqtt_password | length > 0
