---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-secret
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: alertmanager-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: PUSHOVER
