---
apiVersion: v1
kind: Service
metadata:
  name: emqx-lb
  namespace: default
  #annotations:
  #  coredns.io/hostname: emqx.{ORG_DOMAIN}
  #labels:
  #  apps.emqx.io/db-role: core
  #  apps.emqx.io/instance: emqx
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: ${SVC_EMQX_ADDR_V4}
  ports:
    - protocol: TCP
      port: 1883
    #- protocol: TCP
    #  port: 8083
    #- protocol: TCP
    #  port: 18083
    #mqtt:
    #  enabled: true
    #  port: 1883
    #  protocol: TCP
    #host-sni:
    #  enabled: true
    #  port: 8083
    #secure:
    #  enabled: true
    #  port: 18083
  selector:
    apps.emqx.io/db-role: core
    apps.emqx.io/instance: emqx
