---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia
  namespace: auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-virtops
  target:
    name: authelia-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Authelia
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .LLDAP_LDAP_USER_PASS }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: "{{ .private_key }}"
        AUTHELIA_JWT_SECRET: "{{ .AUTHELIA_JWT_SECRET }}"
        AUTHELIA_SESSION_SECRET: "{{ .AUTHELIA_SESSION_SECRET }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}"
        AUTHELIA_NOTIFIER_SMTP_USERNAME: "{{ .AUTHELIA_NOTIFIER_SMTP_USERNAME }}"
        AUTHELIA_NOTIFIER_SMTP_PASSWORD: "{{ .AUTHELIA_NOTIFIER_SMTP_PASSWORD }}"
        AUTHELIA_NOTIFIER_SMTP_ADDRESS: "{{ .AUTHELIA_NOTIFIER_SMTP_ADDRESS }}"
        # OIDC Apps
        GRAFANA_OAUTH_CLIENT_SECRET: "{{ .GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET }}"
        IMMICH_OAUTH_CLIENT_SECRET: "{{ .IMMICH_OAUTH_CLIENT_SECRET }}"
        #MINIFLUX_OAUTH_CLIENT_SECRET: "{{ .MINIFLUX_OAUTH_CLIENT_SECRET }}"
        #WEAVEGITOPS_OAUTH_CLIENT_SECRET: "{{ .WEAVEGITOPS_OAUTH_CLIENT_SECRET }}"
        #GITEA_OAUTH_CLIENT_SECRET: "{{ .GITEA_OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: AUTHELIA
    - extract:
        key: AUTHELIA_KEYS
    - extract:
        key: LLDAP
    
