---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authelia
  namespace: auth
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 2
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/authelia/authelia
      tag: master@sha256:8333f69fc566632e89cf06ab28dfcbc17eb129fbc7bd6a314373a2587069cdcb
    args: ["--config", "/config/configuration.yaml", "--config.experimental.filters", "expand-env"]
    env:
      AUTHELIA_AUTHENTICATION_BACKEND_PASSWORD_RESET_DISABLE: "true"
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_GROUPS_DN: ou=groups
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_USERS_DN: ou=people
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: dc=home,dc=arpa
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_DISPLAY_NAME: displayName
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_GROUPS_FILTER: (member={dn})
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_GROUP_NAME: cn
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_IMPLEMENTATION: custom
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_MAIL: mail
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_START_TLS: "false"
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_TIMEOUT: 5s
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDRESS: ldap://lldap.auth.svc.cluster.local:389
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: uid=admin,ou=people,dc=home,dc=arpa
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_USERNAME: uid
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USERS_FILTER: (&({username_attribute}={input})(objectClass=person))
      AUTHELIA_DEFAULT_REDIRECTION_URL: https://auth.${ORG_DOMAIN}
      AUTHELIA_DUO_API_DISABLE: "true"
      AUTHELIA_LOG_LEVEL: info
      AUTHELIA_NOTIFIER_SMTP_SENDER: "Authelia <noreply@${NET_DOMAIN}>"
      AUTHELIA_NOTIFIER_DISABLE_STARTUP_CHECK: "true"
      AUTHELIA_SERVER_DISABLE_HEALTHCHECK: "true"
      AUTHELIA_SERVER_ADDRESS: tcp://:80
      AUTHELIA_SESSION_DOMAIN: ${ORG_DOMAIN}
      AUTHELIA_SESSION_REDIS_DATABASE_INDEX: 14
      AUTHELIA_SESSION_REDIS_HOST: redis.default.svc.cluster.local
      AUTHELIA_TELEMETRY_METRICS_ADDRESS: "tcp://0.0.0.0:8080"
      AUTHELIA_TELEMETRY_METRICS_ENABLED: "true"
      AUTHELIA_THEME: grey
      AUTHELIA_TOTP_ISSUER: authelia.com
      AUTHELIA_WEBAUTHN_DISABLE: "true"
      AUTHELIA_STORAGE_POSTGRES_DATABASE:
        valueFrom:
          secretKeyRef:
            name: database-authelia-user
            key: DATABASE_NAME
      AUTHELIA_STORAGE_POSTGRES_ADDRESS: postgres.database.svc.cluster.local:5432
      AUTHELIA_STORAGE_POSTGRES_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: database-authelia-user
            key: PASSWORD
      AUTHELIA_STORAGE_POSTGRES_USERNAME:
        valueFrom:
          secretKeyRef:
            name: database-authelia-user
            key: LOGIN
    envFrom:
      - secretRef:
          name: authelia-secret
    enableServiceLinks: false
    service:
      main:
        ports:
          http:
            port: &port 80
          metrics:
            enabled: true
            port: 8080
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /api/health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.${ORG_DOMAIN}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            add_header Cache-Control "no-store";
            add_header Pragma "no-cache";
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-XSS-Protection "1; mode=block";
          hajimari.io/icon: mdi:shield-account
        hosts:
          - host: &host auth.${ORG_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        type: configMap
        name: authelia-configmap
        subPath: configuration.yaml
        mountPath: /config/configuration.yaml
        readOnly: false
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 100Mi
