---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sabnzbd-gatus-ep
  namespace: media
  labels:
    gatus.io/enabled: "true"
data:
  #config.yaml: |
  #  endpoints:
  #    - name: sabnzbd
  #      group: guarded
  #      url: 1.1.1.1
  #      interval: 1m
  #      dns:
  #        query-name: sabnzbd.${ORG_DOMAIN}
  #        query-type: A
  #      conditions:
  #        - "len([BODY]) == 0"
  #      alerts:
  #        - type: pushover
  config.yaml: |
    endpoints:
      - name: sabnzbd
        group: external
        url: https://sabnzbd.${ORG_DOMAIN}
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
